---
title: "Open Reproducible Research at UJI"
---

## Timeline

The UJI and Spain's national funding and evaluation agencies in general are recently taking key steps towards open and transparent science.


::: {.column-margin}
Since 2020, the UJI has organised an annual workshop on Ethics in Research (*[Jornadas de Ética de la Investigación](https://www.uji.es/investigacio/base/etica/recursosformatius/jornades/)*), including topics such as CoARA, open science, and research integrity. Guest speakers presentations are [publicy available](https://www.uji.es/investigacio/base/etica/recursosformatius/jornades/videosessions/).
::::

-   **October 2020, UJI**: Institutional statement to promote open access [Declaración institucional a favor de la promoción del acceso abierto en la Universitat Jaume I](http://www.uji.es/upo/rest/contenido/630998650/raw?idioma=es).

-   **April 2021, AEI**: [Agencia Estatal de Investigación](https://www.aei.gob.es/) (AEI) adhered to the [DORA Declaration](https://sfdora.org/) about research assessment with the commitment to “review all calls and documents supporting the evaluation to ensure their correct implementation”.

::: {.callout-note collapse="true"}
## DORA recommendations that AEI promises to carry out

-   **Do not use journal-based metrics, such as impact factor, as a surrogate measure of the quality of individual research articles**, to evaluate the contributions of an individual scientist, or in hiring, promotion, or funding decisions.

-   Be explicit about the criteria used to evaluate the scientific productivity of research funding applicants, especially for researchers who are beginning their research career, that the **scientific content of a paper is much more important than publication metrics or the identity of the article. the magazine in which it was published**.

-   **Consider the value and impact of all research results (including data sets and software)** in addition to research publications, and consider a wide range of impact measures including indicators qualitative, such as influence on scientific policy and practices.
:::

-   **October 2022, UJI**: [Código de Buenas Prácticas en Investigación y Doctorado (CBPID) 2022](https://www.uji.es/upo/rest/contenido/1102833261/raw?idioma=es).

-   **March 2023, UJI**: UJI adhered to the CoARA Coalition for Advancing Research Assessment ([COARA](https://coara.eu/)).

::: {.callout-note collapse="true"}
## Agreement on Reforming Research Assessment (ARRA) & CoARA

[ARRA](https://coara.eu/agreement) = 10 principles + 10 commitments

::: panel-tabset
## 10 Principles

1.  Comply with ethics and integrity rules and practices
2.  Safeguard freedom of scientific research
3.  Respect the autonomy of research organisations
4.  Ensure independence and transparency of the data, infrastructure and criteria necessary for research assessment
5.  Focus research assessment criteria on quality
6.  Recognise the contributions that advance knowledge and impact
7.  Recognise the diversity of research activities, practices, and outputs
8.  Respect the variety of scientific disciplines, research types, and research career stages
9.  Acknowledge and valorise the diversity in research roles and careers
10. Ensure gender equality, equal opportunities and inclusiveness

## 10 Commitments

1.  Recognise the diversity of contributions to, and careers in, research
2.  Base research assessment primarily on qualitative evaluation for which peer review is central
3.  Abandon inappropriate uses in research assessment of journal- and publication-based metrics
4.  Avoid the use of rankings of research organisations in research assessment
5.  Commit resources to reforming research assessment
6.  Review and develop research assessment criteria, tools and processes
7.  Raise awareness of research assessment reform and provide transparent communication, guidance, and training on assessment criteria and processes as well as their use
8.  Exchange practices and experiences
9.  Communicate progress made on adherence to the Principles and implementation of the Commitments
10. Evaluate practices, criteria and tools, and make data openly available for evidence
:::

As a community, [CoARA](https://coara.eu/) will develop and apply changes
:::

-   **April 2023, ANECA**: [ANECA adhered to DORA and CoARA](https://www.aneca.es/-/aneca-se-adhiere-a-la-san-francisco-declaration-on-research-assessment-dora-y-a-la-coalition-for-advancing-research-assessment-coara-).

-   **May 2023, Ministry of Science**: published the [National Strategy for Open Science (ENCA) 2023-2027](https://www.ciencia.gob.es/Estrategias-y-Planes/Estrategias/ENCA.html), with the "mission of strengthening the quality, transparency, and reproducibility of scientific activity in Spain".

-   **July 2023, ANECA-CRUE**: Proposal of the [CoARA National Chapter Spain](https://coara.eu/app/uploads/2023/12/National-Chaptern-Spain.pdf).

-   **November 2023, National Committee of Research Ethics**: published ["Recomendaciones éticas para la investigación en IA"](https://www.ciencia.gob.es/InfoGeneralPortal/documento/cedef913-3842-4f90-9ffc-032d256125f0).

-   **December 2023, ANECA**: published [new criteria for SEXENIOS assessment](https://www.aneca.es/convocatoria-2023), which are a first attempt to align with the CoARA principles.

-   **February 2024, ANECA-CRUE**: Kick-off the [CoARA Spanish National Chapter](https://coara.eu/coalition/national-chapters/coara-national-chapter-spain/)

-   **March 2024, ANECA**: published [new criteria for accreditation](https://www.aneca.es/documents/20123/53669/Criterios200324_anexos.pdf/470f9b03-fd7a-85b6-4f3a-1925c0f82c50?t=1711094067735) to associate professor and full professor, which are a first attempt to align with the CoARA principles.

-   **April 2024, UJI**: published a roadmap document called ["Action Plan CoARA 2024-2027"](https://www.uji.es/investigacio/base/coara/noticies/pla_accio/SLT_FM_ES_CoARA_UJI.pdf)" that specifies the development of diagnosis-evaluation-implementation activities to improve research assessment at the UJI.

-  **May 2024, UJI**: published a document called ["Plan de Acción en el marco de la Estrategia Nacional de Ciencia Abierta (2023-2027)"](https://www.uji.es/upo/rest/contenido/1039818540/raw?idioma=es).

-   **June 2024, UJI**: set up an institutional web site ["Evaluación de la actividad investigadora (CoARA-UJI)"](https://www.uji.es/investigacio/base/coara/) to provide information about the CoARA initiative and the activities at UJI to align with its principles and commitments. This web site includes action plan to adapt research assessment activities at UJI according to CoARA frame.

-   **Sep-Oct 2024, UJI**: published ["Termómetro del acceso abierto de la UJI 2023-2024"](https://www.uji.es/investigacio/base/enca/noticies/termometre/informe_cas.pdf), which reports about the current situation of engagment in open access by UJI researchers. 

-   **Oct 2024, UJI**: set up an institutional web site ["Estrategia de Ciencia Abierta (ENCA-UJI)"](https://www.uji.es/investigacio/base/enca/) to provide information about the activities at UJI to align with the ENCA actions.

-   **Mar 2025, UJI**: published the results of the Survey on Open Science at UJI available as a brief summary ["Breve informe sobre la encuesta ¿Qué pensamos sobre la evaluación científica de nuestra investigación?"](http://hdl.handle.net/10234/745519).

-   **July 2025, UJI**: ["Código de Buenas Prácticas en Investigación y Doctorado (CBPID) 2025"](https://www.uji.es/investigacio/base/etica/cbpid/).

-   **April 2026, UJI**: ["Informe sobre els processos d’avaluació de l’activitat
investigadora de la Universitat Jaume I"](). As a response to an item in ["Action Plan CoARA 2024-2027"](https://www.uji.es/investigacio/base/coara/noticies/pla_accio/SLT_FM_ES_CoARA_UJI.pdf), this ongoing, informative study reports about the current situation of research assessment at UJI, including the criteria used in different evaluation processes, suggestions to update them to the CoARA frame, and the opinions of researchers about these processes.



## What UJI recommends

As part of the [Open Knowledge Portal](https://www.uji.es/serveis/cd/bib/pco/), the UJI library provides guides for researchers about 

- [how to publish open access](https://www.uji.es/serveis/cd/bib/serveis/investigacio/oa/), including information about the different types of open access, the benefits of publishing open access, and the steps to publish open access.

- [support guidelines to manage and publish research data](https://www.uji.es/serveis/cd/bib/serveis/investigacio/dades/?), including information about the importance of research data management, the steps to manage and publish research data, and the resources available to support researchers in this process.

- [copyright and licenses](https://www.uji.es/serveis/cd/bib/pco/base/drets2/), including information about the different types of licenses and how to choose the appropriate license for research outputs.


| As regards...            | ...UJI recommends (July 2025) |
|----------------------|--------------------------------------------------|
| **Sharing publications** [[source](https://www.uji.es/serveis/cd/bib/serveis/investigacio/oa/)]     | Mandatory archival of journal articles (*publisher's final paper* > *postprint* > *preprint* ) in the [institutional repository](https://repositori.uji.es/). Also recommended other types of publications (book chapters, conference papers, etc.) |
| **Publication licences** [[source](https://www.uji.es/serveis/cd/bib/pco/base/drets2/)]    | CC BY-SA (TFG, TFM, PhD) CC BY-SA-NC (PhD, Educational resources)  |
| **Data licences** [[source](https://www.uji.es/serveis/cd/bib/serveis/investigacio/dades/?)]            | Researchers can choose between CC licences or copyright licences (potential commercial value).|
| **Software licences**  [[Source](https://ujiapps.uji.es/ade/rest/storage/9E7UL1LGULHCGZTNSEO0CSGO2NCWUFGT)]      | Researchers can choose between permissive licences or copyright licences (potential commercial value). |
| **Data FAIR principles** [[Source](https://ujiapps.uji.es/ade/rest/storage/9E7UL1LGULHCGZTNSEO0CSGO2NCWUFGT)]     | Whenever possible, researchers will apply FAIR principles to research data and deposit it in open access (institutional) repositories |
| **Software FAIR principles** [[Source](https://ujiapps.uji.es/ade/rest/storage/9E7UL1LGULHCGZTNSEO0CSGO2NCWUFGT)] | Whenever possible, deposit software results/tools in open access (instituational) repositories. (*Note: Nothing about FAIR principles for software*) |


Regarding research data, the UJI library provides [specific guidelines for small and large datasets](https://www.uji.es/serveis/cd/bib/serveis/investigacio/dades/?), which are summarised in the following table:

| Feature | Small Datasets (<500 MB) | Large Datasets (500 MB - 50 GB) |
|---------|--------------------------|---------------------------------|
| **Primary platform** | [UJI Repository (Investigació)](https://repositori.uji.es/handle/10234/9) | ZENODO ([UJI Community](https://zenodo.org/communities/universitatjaumei/?page=1&size=20))|
| **Used identifier** | Handler | DOI |
| **Required files** | Dataset + Readme.txt | Dataset + Readme.txt |
| **Preferred license** | CC-BY / CC-0 | CC-BY / CC-0 |